import 'dart:math';

String getRandomQuote() {
  final List<String> quotes = [
    "Life is like a 10-speed bicycle. Most of us have gears we never use. - Charles M. Schulz",
    "When the spirits are low, when the day appears dark, when work becomes monotonous, just mount a bicycle and go out for a spin down the road, without thought on anything but the ride you are taking. - Arthur Conan Doyle",
    "Riding a bike is like an art, something you do because you feel something inside. - Valentino Rossi",
    "Bicycles may change, but cycling is timeless. - Zapata Espinoza",
    "You can't be sad while riding a bicycle. - Unknown",
    "I have always struggled to achieve excellence. One thing that cycling has taught me is that if you can achieve something without a struggle, it's not going to be satisfying. - Greg LeMond",
    "Life is better when you pedal. - Unknown",
    "I don't ride a bike to add days to my life. I ride a bike to add life to my days. - Unknown",
    "The best rides are the ones where you bite off much more than you can chew, and live through it. - Doug Bradbury",
    "When in doubt, pedal it out. - Unknown",
    "The bicycle is just as good company as most husbands and, when it gets old and shabby, a woman can dispose of it and get a new one without shocking the entire community. - Ann Strong",
    "Cyclists see considerably more of this beautiful world than any other class of citizens. - Dr. K.K. Doty",
    "Bicycling is the nearest approximation I know to the flight of birds. - Louis J. Helle",
    "Life is short, ride your bike. - Unknown",
    "To me, it doesn't matter whether it's raining or the sun is shining or whatever: as long as I'm riding a bike, I know I'm the luckiest guy in the world. - Mark Cavendish",
    "A bicycle ride is a flight from sadness. - James E. Starrs",
    "When your legs scream stop and your lungs are bursting, that's when it starts. That's the hurt locker. Winners love it in there. - Chris McCormack",
    "Ride your bike, ride your bike, ride your bike. - Fausto Coppi",
    "Bicycles are almost as good as guitars for meeting girls. - Bob Weir",
    "Bicycles may change, but cycling is timeless. - Zapata Espinoza",
    "It is the unknown around the corner that turns my wheels. - Heinz Stucke",
    "The best rides are the ones where you bite off much more than you can chew and live through it. - Doug Bradbury",
    "Don't buy upgrades, ride up grades. - Eddy Merckx",
    "Riding bicycles will not only benefit the individual doing it, but the world at large. - Udo E. Simonis",
    "Life is like a 10-speed bicycle. Most of us have gears we never use. - Charles M. Schulz",
    "When the spirits are low, when the day appears dark, when work becomes monotonous, just mount a bicycle and go out for a spin down the road, without thought on anything but the ride you are taking. - Arthur Conan Doyle",
    "Riding a bike is like an art, something you do because you feel something inside. - Valentino Rossi",
    "Bicycles may change, but cycling is timeless. - Zapata Espinoza",
    "You can't be sad while riding a bicycle. - Unknown",
    "I have always struggled to achieve excellence. One thing that cycling has taught me is that if you can achieve something without a struggle, it's not going to be satisfying. - Greg LeMond",
    "Life is better when you pedal. - Unknown",
    "I don't ride a bike to add days to my life. I ride a bike to add life to my days. - Unknown",
    "The best rides are the ones where you bite off much more than you can chew, and live through it. - Doug Bradbury",
    "When in doubt, pedal it out. - Unknown",
    "The bicycle is just as good company as most husbands and, when it gets old and shabby, a woman can dispose of it and get a new one without shocking the entire community. - Ann Strong",
    "Cyclists see considerably more of this beautiful world than any other class of citizens. - Dr. K.K. Doty",
    "Bicycling is the nearest approximation I know to the flight of birds. - Louis J. Helle",
    "Life is short, ride your bike. - Unknown",
    "To me, it doesn't matter whether it's raining or the sun is shining or whatever: as long as I'm riding a bike, I know I'm the luckiest guy in the world. - Mark Cavendish",
    "A bicycle ride is a flight from sadness. - James E. Starrs",
    "When your legs scream stop and your lungs are bursting, that's when it starts. That's the hurt locker. Winners love it in there. - Chris McCormack",
    "Ride your bike, ride your bike, ride your bike. - Fausto Coppi",
    "Bicycles are almost as good as guitars for meeting girls. - Bob Weir",
    "Riding a bike is the same as riding a flying unicorn through a galaxy made of chocolate. - Unknown",
    "When I'm riding my bicycle, I feel like a Buddhist who is happy just to enjoy his mundane existence. - Robin Williams",
    "The bicycle is a curious vehicle. Its passenger is its engine. - John Howard",
    "The bicycle is a simple solution to some of the world's most complicated problems. - Unknown",
    "A bicycle ride around the world begins with a single pedal stroke. - Scott Stoll",
    "The bicycle is a curious vehicle. Its passenger is its engine. - John Howard",
    "The bicycle is a simple solution to some of the world's most complicated problems. - Unknown",
    "A bicycle ride around the world begins with a single pedal stroke. - Scott Stoll",
    "I have too many bikes. - Said no cyclist ever.",
    "Ride as much or as little, or as long or as short as you feel. But ride. - Eddy Merckx",
    "The bicycle is just as good company as most husbands and, when it gets old and shabby, a woman can dispose of it and get a new one without shocking the entire community. - Ann Strong",
    "Bicycling is the nearest approximation I know to the flight of birds. - Louis J. Helle",
    "Life is short, ride your bike. - Unknown",
    "I don't ride a bike to add days to my life. I ride a bike to add life to my days. - Unknown",
    "The best rides are the ones where you bite off much more than you can chew, and live through it. - Doug Bradbury",
    "When in doubt, pedal it out. - Unknown",
    "You can't be sad while riding a bicycle. - Unknown",
    "Riding bicycles will not only benefit the individual doing it, but the world at large. - Udo E. Simonis",
    "Don't buy upgrades, ride up grades. - Eddy Merckx",
    "The best rides are the ones where you bite off much more than you can chew and live through it. - Doug Bradbury",
    "It is the unknown around the corner that turns my wheels. - Heinz Stucke",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "A bicycle ride is a flight from sadness. - James E. Starrs",
    "When the spirits are low, when the day appears dark, when work becomes monotonous, just mount a bicycle and go out for a spin down the road, without thought on anything but the ride you are taking. - Arthur Conan Doyle",
    "Riding a bike is like an art, something you do because you feel something inside. - Valentino Rossi",
    "Bicycles may change, but cycling is timeless. - Zapata Espinoza",
    "Life is like a 10-speed bicycle. Most of us have gears we never use. - Charles M. Schulz",
    "To me, it doesn't matter whether it's raining or the sun is shining or whatever: as long as I'm riding a bike, I know I'm the luckiest guy in the world. - Mark Cavendish",
    "When your legs scream stop and your lungs are bursting, that's when it starts. That's the hurt locker. Winners love it in there. - Chris McCormack",
    "Ride your bike, ride your bike, ride your bike. - Fausto Coppi",
    "Bicycles are almost as good as guitars for meeting girls. - Bob Weir",
    "Riding a bike is the same as riding a flying unicorn through a galaxy made of chocolate. - Unknown",
    "When I'm riding my bicycle, I feel like a Buddhist who is happy just to enjoy his mundane existence. - Robin Williams",
    "The bicycle is a curious vehicle. Its passenger is its engine. - John Howard",
    "The bicycle is a simple solution to some of the world's most complicated problems. - Unknown",
    "A bicycle ride around the world begins with a single pedal stroke. - Scott Stoll",
    "I have too many bikes. - Said no cyclist ever.",
    "Ride as much or as little, or as long or as short as you feel. But ride. - Eddy Merckx",
    "The bicycle is just as good company as most husbands and, when it gets old and shabby, a woman can dispose of it and get a new one without shocking the entire community. - Ann Strong",
    "Bicycling is the nearest approximation I know to the flight of birds. - Louis J. Helle",
    "Life is short, ride your bike. - Unknown",
    "I don't ride a bike to add days to my life. I ride a bike to add life to my days. - Unknown",
    "The best rides are the ones where you bite off much more than you can chew, and live through it. - Doug Bradbury",
    "When in doubt, pedal it out. - Unknown",
    "You can't be sad while riding a bicycle. - Unknown",
    "Riding bicycles will not only benefit the individual doing it, but the world at large. - Udo E. Simonis",
    "Don't buy upgrades, ride up grades. - Eddy Merckx",
    "The best rides are the ones where you bite off much more than you can chew and live through it. - Doug Bradbury",
    "It is the unknown around the corner that turns my wheels. - Heinz Stucke",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "A bicycle ride is a flight from sadness. - James E. Starrs",
    "When the spirits are low, when the day appears dark, when work becomes monotonous, just mount a bicycle and go out for a spin down the road, without thought on anything but the ride you are taking. - Arthur Conan Doyle",
    "Riding a bike is like an art, something you do because you feel something inside. - Valentino Rossi",
    "Bicycles may change, but cycling is timeless. - Zapata Espinoza",
    "Life is like a 10-speed bicycle. Most of us have gears we never use. - Charles M. Schulz",
    "To me, it doesn't matter whether it's raining or the sun is shining or whatever: as long as I'm riding a bike, I know I'm the luckiest guy in the world. - Mark Cavendish",
    "When your legs scream stop and your lungs are bursting, that's when it starts. That's the hurt locker. Winners love it in there. - Chris McCormack",
    "Ride your bike, ride your bike, ride your bike. - Fausto Coppi",
    "Bicycles are almost as good as guitars for meeting girls. - Bob Weir",
    "Riding a bike is the same as riding a flying unicorn through a galaxy made of chocolate. - Unknown",
    "When I'm riding my bicycle, I feel like a Buddhist who is happy just to enjoy his mundane existence. - Robin Williams",
    "The bicycle is a curious vehicle. Its passenger is its engine. - John Howard",
    "The bicycle is a simple solution to some of the world's most complicated problems. - Unknown",
    "A bicycle ride around the world begins with a single pedal stroke. - Scott Stoll",
    "I have too many bikes. - Said no cyclist ever.",
    "Ride as much or as little, or as long or as short as you feel. But ride. - Eddy Merckx",
    // Add more quotes as needed
  ];

  final Random random = Random();
  final int randomIndex = random.nextInt(quotes.length);

  return quotes[randomIndex];
}
